GET http://{{address}}/api/item?id={{address}}
Accept: application/json
Authorization: Basic {{user}} {{password}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET localhost:9000

aleksandrgurkin
8d6192a9-4a97-4d8c-a2ad-9444d7f0ccb3